[package]
name = "klarna_mail_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mail-parser = "0.8.2"
csv = "1.2.1"
regex = "1.7.3"
lazy_static = "1.4.0"
chrono = "0.4.24"
indicatif = "0.17.3"